name: Github Action which will tag the commit with the version number
on:
  push:
    branches:
      - master
permissions:
  contents: read
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
    tag:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout the repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            fetch-tags: true
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.13
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install commitizen
        - name: show git log
          run: git log -5 --oneline
        - name: commitizen dry run
          run: |
            cz bump --dry-run --yes 2>/dev/null
            echo "cz-bump-dry-run-exit-code=$?" >> $GITHUB_OUTPUT
        - name: commitizen bump
          run: |
            cz bump --yes 2>/dev/null
            echo "cz-bump-exit-code=$?" >> $GITHUB_OUTPUT
